export const ParagraphList = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamco laboris nisi ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "Incididunt ut labore et dolore magna aliqua. Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Sit amet consectetur adipiscing elit sed do eiusmod tempor. Dolor sit amet consectetur adipiscing elit. Ut labore et dolore magna aliqua. Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum sit amet consectetur adipiscing elit.",
  "Adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet consectetur. Labore et dolore magna aliqua. Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt.",
  "Consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet. Tempor incididunt ut labore et dolore magna aliqua. Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Sit amet consectetur adipiscing elit sed do eiusmod.",
  "As she walked through the bustling city streets, she couldn't help but be captivated by the vibrant energy that surrounded her. People from all walks of life hurried past, their footsteps echoing on the pavement. The aroma of freshly brewed coffee wafted from the nearby cafes, enticing her senses. It was a city that never slept, always alive with endless possibilities.",
  "The sky was painted in hues of orange and pink as the sun began to set behind the distant mountains. A gentle breeze rustled the leaves of the trees, creating a soothing melody. Birds chirped happily, their songs filling the air with a sense of tranquility. It was a perfect evening for a leisurely stroll along the riverbank. The pages of the book turned with a satisfying whisper, transporting the reader to a world of imagination and wonder. With each word, the characters came to life, their stories unfolding before her eyes. She was captivated by the author's ability to create such vivid landscapes and compelling narratives. Lost in the pages, she eagerly awaited the next chapter.",
  "The waves crashed against the shore, sending sprays of water into the air. The salty sea breeze tousled her hair as she stood on the cliff, gazing out at the endless horizon. Seagulls soared gracefully overhead, their cries blending with the sound of the ocean. It was a scene of raw beauty, a reminder of the vastness and power of nature. The aroma of freshly baked bread filled the kitchen, drawing everyone to the table. The family gathered, their laughter and conversation filling the room. The table was adorned with an array of delicious dishes, each one made with love and care. It was a time of togetherness, where bonds were strengthened and memories were created.",
];
